config/routes.rb
Rails.application.routes.draw do
  resources :logins
  namespace :index do
    resources :people
  end

  get 'single_image' => 'single_image'
  put "single_image/liking", to: 'single_image#liking'
  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/index.rb
module Index
  def self.table_name_prefix
    'index_'
  end
end

app/models/index/person.rb
class Index::Person < ActiveRecord::Base
end

app/models/login.rb
class Login < ActiveRecord::Base
end

app/models/slide.rb
class Slide < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index/people_controller.rb
class Index::PeopleController < ApplicationController
  before_action :set_index_person, only: [:show, :edit, :update, :destroy]

  # GET /index/people
  # GET /index/people.json
  def index
    @index_people = Index::Person.all
  end

  # GET /index/people/1
  # GET /index/people/1.json
  def show
  end

  # GET /index/people/new
  def new
    @index_person = Index::Person.new
  end

  # GET /index/people/1/edit
  def edit
  end

  # POST /index/people
  # POST /index/people.json
  def create
    @index_person = Index::Person.new(index_person_params)

    respond_to do |format|
      if @index_person.save
        format.html { redirect_to @index_person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @index_person }
      else
        format.html { render :new }
        format.json { render json: @index_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /index/people/1
  # PATCH/PUT /index/people/1.json
  def update
    respond_to do |format|
      if @index_person.update(index_person_params)
        format.html { redirect_to @index_person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @index_person }
      else
        format.html { render :edit }
        format.json { render json: @index_person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /index/people/1
  # DELETE /index/people/1.json
  def destroy
    @index_person.destroy
    respond_to do |format|
      format.html { redirect_to index_people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_index_person
      @index_person = Index::Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def index_person_params
      params.require(:index_person).permit(:name, :age)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:name, :pass)
    end
end

app/controllers/single_image_controller.rb
class SingleImageController < ApplicationController
	def single_image
		@image = Slide.find_by(id: 1).image 
		@likes = Slide.find_by(id: 1).likes
		@comm = Comment.all.to_a
	end
	def liking
		numOfLikes = Slide.find_by(id: 1).likes
		Slide.find_by(id: 1).update(likes: numOfLikes+1 )
		redirect_to :single_image
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index/people_helper.rb
module Index::PeopleHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/single_image_helper.rb
module SingleImageHelper
end

app/views/index/people/_form.html.erb
<%= form_for(@index_person) do |f| %>
  <% if @index_person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@index_person.errors.count, "error") %> prohibited this index_person from being saved:</h2>

      <ul>
      <% @index_person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/index/people/edit.html.erb
<h1>Editing Index Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @index_person %> |
<%= link_to 'Back', index_people_path %>

app/views/index/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Index People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @index_people.each do |index_person| %>
      <tr>
        <td><%= index_person.name %></td>
        <td><%= index_person.age %></td>
        <td><%= link_to 'Show', index_person %></td>
        <td><%= link_to 'Edit', edit_index_person_path(index_person) %></td>
        <td><%= link_to 'Destroy', index_person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_index_person_path %>

app/views/index/people/new.html.erb
<h1>New Index Person</h1>

<%= render 'form' %>

<%= link_to 'Back', index_people_path %>

app/views/index/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @index_person.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @index_person.age %>
</p>

<%= link_to 'Edit', edit_index_person_path(@index_person) %> |
<%= link_to 'Back', index_people_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :pass %><br>
    <%= f.text_field :pass %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logins</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pass</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.name %></td>
        <td><%= login.pass %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @login.name %>
</p>

<p>
  <strong>Pass:</strong>
  <%= @login.pass %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/single_image/single_image.html.erb
<%= image_tag( @image , size: "400x300", alt: "slide") %> 
</br>
likes: <%= @likes %>
</br>
<% nothing = 1 %>
  <%= link_to("Like", "single_image/liking", method: :put) %>
<table>

<% counter = 1
@comm.each do |sing_comm|%>
<tr> <%=  counter %> <%=  ") " + sing_comm.comment %> </tr>
<% counter+= 1 %>
</br>
<% end %>

	
</table>